// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3SqRSb6FYJFBOuCEa3Is5KcHAbRR7uHg',
    appId: '1:7523118923:web:7ab054a987d845a816c2ce',
    messagingSenderId: '7523118923',
    projectId: 'signinsignup-66ac7',
    authDomain: 'signinsignup-66ac7.firebaseapp.com',
    storageBucket: 'signinsignup-66ac7.appspot.com',
    measurementId: 'G-WXCMW4P15R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeT2721zPgYg__WnlYNbSO-ypc6-lUe-M',
    appId: '1:7523118923:android:d849d30a427c84c116c2ce',
    messagingSenderId: '7523118923',
    projectId: 'signinsignup-66ac7',
    storageBucket: 'signinsignup-66ac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjrNApkKSh3qBUEnq4GNdvO5J9FnsTs4c',
    appId: '1:7523118923:ios:621173a71bc1d5a316c2ce',
    messagingSenderId: '7523118923',
    projectId: 'signinsignup-66ac7',
    storageBucket: 'signinsignup-66ac7.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3SqRSb6FYJFBOuCEa3Is5KcHAbRR7uHg',
    appId: '1:7523118923:web:3c294ffbba91bdc616c2ce',
    messagingSenderId: '7523118923',
    projectId: 'signinsignup-66ac7',
    authDomain: 'signinsignup-66ac7.firebaseapp.com',
    storageBucket: 'signinsignup-66ac7.appspot.com',
    measurementId: 'G-67VNBKLRHS',
  );
}
